# Generated by Django 3.1.2 on 2020-11-01 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='time',
            field=models.IntegerField(default=0),
        ),
    ]
